title: dotnet interview
description: Dotnet interview questions and answers
theme: just-the-docs

url: "https://abaniuszewicz.github.io"

callouts_level: quiet
callouts:
  def:
    title: Definicja
    color: purple

aux_links:
  "github.com/abaniuszewicz":
    - "//github.com/abaniuszewicz"

collections_dir: content