name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-interview.pdf
          path: main.pdf
          if-no-files-found: error
      - name: Commit pdf
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: publish pdf file
          file_pattern: *.pdf
