name: Publish dotnet-interview.pdf
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: dotnet-interview.tex
      - name: Release pdf
        uses: softprops/action-gh-release@v1
        with:
          files: dotnet-interview.pdf